### ISSUE TITLE
pip install imutils on BeagleBoard-X15

### ISSUE THREAD

**Issue by TucsonYazdi** [jrosebr1/imutils#136]
I'm trying to install imutils with python2.7 on a BeagleBoard-X15 and getting the output shown below.  Can you help decode these errors?  Note, I can install imutils in python3.5(pip3 install imutils). However when imutils tries to import cv2 (in python3.5), it fails.  Converserly, I am able to import cv2 under python2.7 but not python3.5.  Kind of a catch-22 situation.

debian@BeagleBoard-X15:~$ pip --version
pip 19.0.3 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)

debian@BeagleBoard-X15:~$ pip install imutils
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting imutils
  Using cached https://files.pythonhosted.org/packages/5e/0c/659c2bdae8e8ca5ef810b9da02db28feaa29ea448ff36b65a1664ff28142/imutils-0.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9cKic1/imutils/setup.py", line 14, in <module>
        scripts=['bin/range-detector'],
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/setuptools/dist.py", line 225, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/setuptools/dist.py", line 257, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/pkg_resources.py", line 2072, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer))
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/pkg_resources.py", line 2282, in requires
        dm = self._dep_map
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/pkg_resources.py", line 2511, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/pkg_resources.py", line 2544, in _compute_dependencies
        common = frozenset(reqs_for_extra(None))
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/pkg_resources.py", line 2541, in reqs_for_extra
        if req.marker_fn(override={'extra':extra}):
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/_markerlib/markers.py", line 109, in marker_fn
        return eval(compiled_marker, environment)
      File "<environment marker>", line 1, in <module>
    NameError: name 'sys_platform' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-9cKic1/imutils/

**Comment by jrosebr1** [comment]
It sounds like there is a problem with your Python environments. You're providing the error installing for Python 2.7 but then saying it doesn't import using Python 3.5? When you say it "fails" for Python 3.5, what is the error?
