### ISSUE TITLE
Failed to install imutils using pip

### ISSUE THREAD

**Issue by gakabani** [jrosebr1/imutils#285]
I apologize if this is a trivial issue. I am no expert in python.
I am unable to install imutils using pip.
My pip version is pip 23.2.1
My python version is Python 3.9.11
I am getting the following error.

gamalakabani:08/01/23:~$ pip install imutils
Collecting imutils
  Using cached imutils-0.5.4.tar.gz (17 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/lc/tbblv6l95sz47jzgk5nkbjyc0000gn/T/pip-install-492yytaq/imutils_36302717c4004751aec4d99d2c2c490a/setup.py", line 3, in <module>
          setup(
        File "/Users/gamalakabani/.pyenv/versions/3.9.11/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/Users/gamalakabani/.pyenv/versions/3.9.11/lib/python3.9/site-packages/setuptools/dist.py", line 496, in __init__
          _Distribution.__init__(
        File "/Users/gamalakabani/.pyenv/versions/3.9.11/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/Users/gamalakabani/.pyenv/versions/3.9.11/lib/python3.9/site-packages/setuptools/dist.py", line 934, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/Users/gamalakabani/.pyenv/versions/3.9.11/lib/python3.9/site-packages/setuptools/dist.py", line 933, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/Users/gamalakabani/.pyenv/versions/3.9.11/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 208, in load
          module = import_module(match.group('module'))
        File "/Users/gamalakabani/.pyenv/versions/3.9.11/lib/python3.9/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
        File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
        File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 850, in exec_module
        File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
        File "/Users/gamalakabani/.pyenv/versions/3.9.11/lib/python3.9/site-packages/npe2/__init__.py", line 9, in <module>
          from ._dynamic_plugin import DynamicPlugin
        File "/Users/gamalakabani/.pyenv/versions/3.9.11/lib/python3.9/site-packages/npe2/_dynamic_plugin.py", line 19, in <module>
          from ._plugin_manager import PluginManager
        File "/Users/gamalakabani/.pyenv/versions/3.9.11/lib/python3.9/site-packages/npe2/_plugin_manager.py", line 30, in <module>
          from ._command_registry import CommandRegistry
        File "/Users/gamalakabani/.pyenv/versions/3.9.11/lib/python3.9/site-packages/npe2/_command_registry.py", line 10, in <module>
          from .manifest import utils
        File "/Users/gamalakabani/.pyenv/versions/3.9.11/lib/python3.9/site-packages/npe2/manifest/__init__.py", line 1, in <module>
          from ._package_metadata import PackageMetadata
        File "/Users/gamalakabani/.pyenv/versions/3.9.11/lib/python3.9/site-packages/npe2/manifest/_package_metadata.py", line 14, in <module>
          class PackageMetadata(BaseModel):
        File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
        File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
        File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
        File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
        File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
        File "/Users/gamalakabani/.pyenv/versions/3.9.11/lib/python3.9/typing.py", line 852, in __subclasscheck__
          return issubclass(cls, self.__origin__)
      TypeError: issubclass() arg 1 must be a class
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
gamalakabani:08/01/23:~$

**Comment by Lzhenz** [comment]
I encountered a similar issue on Python 3.12

You can try installing using the following method

`pip install setuptools`

and

`pip install wheel`

Finally, reinstall imutils

`pip install imutils`

good luck
