### ISSUE TITLE
instapy - cannot import name 'log_uncertain_unfollowed_pool' 

### ISSUE THREAD

**Issue by mdavis184** [jrosebr1/imutils#48]
C:\Users\User\Downloads\InstaPy-master>python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Users\User\Downloads\InstaPy-master\instapy\__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "C:\Users\User\Downloads\InstaPy-master\instapy\instapy.py", line 35, in <module>
    from .unfollow_util import get_given_user_followers
  File "C:\Users\User\Downloads\InstaPy-master\instapy\unfollow_util.py", line 12, in <module>
    from .print_log_writer import log_uncertain_unfollowed_pool
ImportError: cannot import name 'log_uncertain_unfollowed_pool' from 'instapy.print_log_writer' (C:\Users\User\Downloads\InstaPy-master\instapy\print_log_writer.py)

**Comment by jrosebr1** [comment]
According to the traceback this isn't a problem with imutils. The traceback starts with:

`from instapy import InstaPy`

You should share with the InstaPy developers. Closing this issue.
