### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'Human semantic parsing for re-identification have a problem..

### ISSUE THREAD

**Issue by hacker-wei** [jrosebr1/imutils#80]
Traceback (most recent call last):
  File "/home/lvv/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/lvv/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/lvv/anaconda2/lib/python2.7/site-packages/chainer/iterators/multiprocess_iterator.py", line 336, in _run
    alive = self._task()
  File "/home/lvv/anaconda2/lib/python2.7/site-packages/chainer/iterators/multiprocess_iterator.py", line 355, in _task
    data_all = future.get(_response_time)
  File "/home/lvv/anaconda2/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by hacker-wei** [comment]
anyone come across this problem???could you help me ?

**Comment by jrosebr1** [comment]
What script are you running? I don't have any examples on human identification here in this repo. Based on your error it doesn't look like any code I offer on the PyImageSearch blog either.

**Comment by hacker-wei** [comment]
"Human semantic parsing for re-identification" 
this paper code.
I could not find this error source .

**Comment by jrosebr1** [comment]
Sorry, I am not familiar with that code. You should contact the authors of the paper directly.

**Comment by hacker-wei** [comment]
ok ，thank you.bro
