### ISSUE TITLE
VideoStream thread dies with PiCamera Value Error

### ISSUE THREAD

**Issue by wb666greene** [jrosebr1/imutils#99]
I'm uisng imutils VideoStream and the PiCamera module for some 24/7 AI code derived from this PyImageSearch tutorial:  [https://www.pyimagesearch.com/2018/05/14/a-gentle-guide-to-deep-learning-object-detection/](url)

It runs great except that at apparently random intervals of from 3-14 days the AI stops working processing an unchanging "stale" image and is thus "blind".   Everything else about the system seems to be working -- ssh, node-red, etc.  A "watchdog" timer added to my main loop doesn't trigger.

I finally managed to trap some error messages after it happens:

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/imutils/video/pivideostream.py", line 31, in update
    for f in self.stream:
  File "/usr/lib/python2.7/dist-packages/picamera/camera.py", line 1710, in capture_continuous
    encoder.close()
  File "/usr/lib/python2.7/dist-packages/picamera/encoders.py", line 431, in close
    self.stop()
  File "/usr/lib/python2.7/dist-packages/picamera/encoders.py", line 419, in stop
    self._close_output()
  File "/usr/lib/python2.7/dist-packages/picamera/encoders.py", line 349, in _close_output
    mo.close_stream(output, opened)
  File "/usr/lib/python2.7/dist-packages/picamera/mmalobj.py", line 371, in close_stream
    stream.flush()
  File "/usr/lib/python2.7/dist-packages/picamera/array.py", line 238, in flush
    self.array = bytes_to_rgb(self.getvalue(), self.size or self.camera.resolution)
  File "/usr/lib/python2.7/dist-packages/picamera/array.py", line 127, in bytes_to_rgb
    'Incorrect buffer length for resolution %dx%d' % (width, height))
PiCameraValueError: Incorrect buffer length for resolution 1296x976
`

Restarting the python code seems to cure the issue until it happens again.  I know its hard to debug problems like this that occur very infrequently.

My short term solution will be the pull the VideoStream source into my code,  add a try block in the thread,  and attempt to figure out how to recover automatically when it happens. 

I'm looking for suggestions on the best way to recover after I catch the exception that is causing the thread to die.

**Comment by jrosebr1** [comment]
Anytime you see an error message with `PiCameraValueError: Incorrect buffer length for resolution 1296x976` it's most of the time due to forgetting to call `stream.truncate(0)`, typically at the end of your `while` loop.

I'm not sure why your code would be executing at all if you forgot that function call but perhaps there is some sort of logic error in there where a certain event occurs and you forget to call it.

**Comment by wb666greene** [comment]
The thread created by imutils videostream  instance is calling stream.truncate(0)   ( as self.rawCapture.truncate(0) )

I posted the comment because I'm totally at a loss as to what is going on other than perhaps a randomly intermittent Picamera module hardware issue, but I observe it with two different systems  P2B and Pi3B with two different production runs of the first generation (5 Mpixel)  camera modules.

I'm weak on the object oriented stuff, but assuming I can trap the exception with a try block, what might be the best way to modify the class to recover from the error?   

Basically what I've done is if I catch the error in the thread, I print an error message and set self.frame to None and in my main loop if the vs.read() returns None,  print another error message to hopefully give me a clue, then continue the loop and see what happens.

Missing a few frames to recover is fine, rebooting also seems to work but this smells of Windows. (Commercial video security software for Windows generally has a scheduled reboot built in!)

Its been 14 days since the system was rebooted and 4 days since I added a try block to the videostream class and restarted the python code.  No errors yet, so I've no idea if my class modifications are doing anything useful or not.  I'll share them if I can make it recover gracefully, but I'm no python guru.

When the mean time to seeing the issue is about a week, progress is very slow!  

I've done the usual "power supply issue" voodoo like going from a 2.2A supply to 2.6A and running it off a UPS which seems to have had no effect on the failure rate.  We had a massive thunderstorm move through and the issue was not triggered.

**Comment by jrosebr1** [comment]
> I'm weak on the object oriented stuff, but assuming I can trap the exception with a try block, what might be the best way to modify the class to recover from the error?

I would try to destroy the existing `VideoStream` object and then re-instantiate it within your `try` block. That will enable you to recover from the error.

I'm honestly not sure what may be causing it. It doesn't sound like it's faulty hardware nor a power supply issue if it's happening on multiple Pi's. My _guess_ is that it's something going on under the hood with the underlying `picamera` module; however, there's not really a good way to debug it. I would take your `try/except` approach and see if you can re-instantiate the object and go from there.

**Comment by wb666greene** [comment]
The error happened again last night, unfortunately my try block didn't catch the exception :(

I've re-positioned the try statement and will try again, I've added code for your suggestion to release and re-instantiate in my except: clause,  basically doing the code in   if self.stopped: delaying for two seconds and redoing the code in __init__()   followed by another two second delay.

It ran for five days, so it'll likely be a good while before I can follow up again with progress or lack thereof.

**Comment by wb666greene** [comment]
After a few fails I have a patch that seems to have solved the PiCamera issue by detecting the error and re-initializing the camera.  Its been running 24/7 since Jan 5th, Today is Feb 27.  My object oriented Python-fu is weak so the notifications of the corrections I was hoping for in my log file never happened so I've no idea how many times its "kicked in" but the system continues to run reliably providing an AI detection about once every 1.8 seconds which is still surprisingly useful because of the very near zero false alarm rate.

I'd be happy to share my patch, but my GitHub-fu is even weaker :)

**Comment by jrosebr1** [comment]
That's great @wb666greene! It's okay if you can't submit a PR but it would be great if you could share the updated `VideoStream` code and relevant code where you call it/utilize it in your driver script. Feel free to copy and paste the code here.

**Comment by wb666greene** [comment]
I need to learn more about actually using GitHub, but today is not the day.

Looks like I was pre-mature about the patch working.  I got the error again on Mar 3rd, it had been running since Jan 5th.  My "watchdog" timer restarted the system (it was in the middle of the night) so I didn't notice until I looked at the log files.

I got the error from the VideoStream class at 2019-03-03_00:01:44.222277  and my Watchdog rebooted the system at 2019-03-03_00:01:57.091621

The VideoStream error exception string is: "Incorrect buffer length for resolution 1296x976"

Maybe ~13 seconds is not long enough to recover?

I've attached the modified class code, in hopes I've made an obvious mistake in the recovery attempt after detecting the error:

```
DISPLAY_DIMS = (1296, 976)     

# modified VideoStream class from imutils library
class PiVideoStream:
    def __init__(self, resolution=(320, 240), framerate=32):
        # initialize the camera and stream
        self.camera = PiCamera()
        self.camera.resolution = resolution
        self.camera.framerate = framerate
        self.rawCapture = PiRGBArray(self.camera, size=resolution)
        self.stream = self.camera.capture_continuous(self.rawCapture, format="bgr", use_video_port=True)


        # initialize the frame and the variable used to indicate if the thread should be stopped
        self.frame = None
        self.stopped = False
        self.error=False

    def start(self):
        # start the thread to read frames from the video stream
        t = Thread(target=self.update, args=())
        t.daemon = True
        t.start()
        return self

    def update(self):
            # keep looping infinitely until the thread is stopped
            try:
                for f in self.stream:
                    # grab the frame from the stream and clear the stream in preparation for the next frame
                    self.frame = f.array
                    self.rawCapture.truncate(0)
                    self.error = False
            except Exception as e:
                self.currentDT = datetime.datetime.now()
                if self.error is False:
                    print(" **** PiCamera error: " + str(e)  + self.currentDT.strftime(" -- %Y-%m-%d_%H_%M_%S.%f"))
                self.error=True
                # attempt to recover
                self.stream.close()
                self.rawCapture.close()
                self.camera.close()
                time.sleep(2)
                self.camera = PiCamera()
                self.camera.resolution = DISPLAY_DIMS
                self.camera.framerate = 32
                self.rawCapture = PiRGBArray(self.camera, size=DISPLAY_DIMS)
                self.stream = self.camera.capture_continuous(self.rawCapture, format="bgr", use_video_port=True)
                time.sleep(2)
                self.frame = None
                    

                # if the thread indicator variable is set, stop the thread and resource camera resources
                if self.stopped:
                    self.stream.close()
                    self.rawCapture.close()
                    self.camera.close()
                    return

    def read(self):
	# return the frame most recently read
	if self.error is False:
            return self.frame
        else:
            return None

    def stop(self):
	# indicate that the thread should be stopped
	self.stopped = True

```

I can see a mistake already, I should not have used DISPLAY_DIMS in the class, but it is the resolution used to instance the class :
`vs = PiVideoStream(resolution=DISPLAY_DIMS).start()`
So I'm guessing its not the reason.

**Comment by wb666greene** [comment]
It slow going to trap a problem and attempt to find a solution when the problem happens maybe once every five weeks on a system running 24/7 that is calling the class method in question about once every 1.5 seconds.

I wouldn't call this Abondoned Work!

I modified my patch above which didn't work, and its taken this long to make progress.  I finally trapped the error:   "Incorrect buffer length for resolution 1296x976"

and observed a correction, meaning the system did not have restart the Python code to get the PiCamera VideoStream capture to recover and return valid images.

I've attached a KDiff3 screenshot of the Original PiVideoStream Class against my modified version.
![KDiff PiVideoStream](https://user-images.githubusercontent.com/31488806/57538586-5b4cb180-730e-11e9-9eb3-9aa90ffdc5c9.png)

I doubt anyone using this class in a non-24/7/365 application is likely to ever encounter the issue, but if others do encounter it,  I may finally have a solution to minimize the downtime and automatically recover.

I'm also attaching the Python code of my PiVideoStream class.
[imutils.VS.class.py.txt](https://github.com/jrosebr1/imutils/files/3167169/imutils.VS.class.py.txt)

**Comment by davidbonn** [comment]
I have stumbled across apparently the same failure.

**Comment by wb666greene** [comment]
I've had this system running with battery backup continuously since 2019-04-27.  Seeing your message I went back and looked at the log files, I've had four of these "PiCamera error: Incorrect buffer length for resolution 1296x976" during the interval 2019-04-27 through 2021-01-03.

  My VideoStream modification seems to have at least succeeded in letting the system recover automatically (without rebooting).  There were a few outages when we had power failures that lasted longer than the UPS battery, but the Pi booted and restarted each time the power came back on.

**Comment by davidbonn** [comment]
You can reproduce this problem much more quickly with a larger image size.  This code generally produces the failure within  few hours on the average, and sometimes within 15-20 minutes:

````
#!/usr/bin/env python3

import time
from imutils.video import VideoStream

def opencamera():
    cam = VideoStream(0, usePiCamera=True,resolution=(2590,1944)).start()

    time.sleep(2.0)

    return cam


if __name__ == '__main__':
        cam = opencamera()
        frame = 0
        while True:
            img = cam.read()

            if img is None:
                break

            frame += 1
            time.sleep(60.0)

            print(f"[verbose] {frame} frames read")

        print(f"[info] exited after {frame} frames")
````

This problem isn't really in `imutils/video` at all, and is more likely in `picamera`.

Again, larger resolutions make this problem happen much more quickly.  I suspect with the HQ camera at full resolution you'd have this happening quite often.

I've pursued a slightly different fix, where I detect that the thread has stopped, clean up the camera resources, and have `read()` return None.  Ideally I'd like `read()` to raise an exception.

One other "fix" is to make a version of `pivideostream` that uses the `picamera.capture()` function rather than the video functions, which while slower will be fine for higher-resolution frame grabs.

A query I made suggesting using a lower `framerate=` parameter when initializing.  My understanding is that this parameter only does anything when recording video or previewing and doesn't matter when grabbing frames.
